# Paperless-ngx:latest inklusive Redis 8 und PostgreSQL 18
# YAML-Dateiversion: 1.10 vom 20.10.2025

# Erstelle  einen Ordner namens "paperless-nxg" im Docker-Verzeichnis. 
# Wechsel in diesen Ordner und erstelle die folgenden Unterordner: 
# data, media, export, consume, pgdata und redisdata.
#
# Die endgültige Verzeichnisstruktur sollte wie folgt aussehen:
# /volume1
#   /docker
#     /paperless-ngx
#       /data
#       /media
#       /export
#       /consume
#       /pgdata
#       /redisdata

services:

# Redis Container
  broker:
    image: docker.io/library/redis:8

    # Name des Redis-Containers (nach Bedarf anpassen)
    container_name: Paperless-ngx-Redis
    restart: unless-stopped

    # Sicherheitsoptionen
    security_opt:
      - no-new-privileges:true

    # Speicherort persistenter Daten (Pfad vor dem Doppelpunkt nach Bedarf anpassen)
    volumes:
      - /volume1/docker/paperless-ngx/redisdata:/data:rw

    # Gesundheitscheck des Redis-Containers
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

# PostgreSQL Container
  db:
    image: docker.io/library/postgres:18

    # Name des PostgreSQL-Containers (nach Bedarf anpassen)
    container_name: Paperless-ngx-PostgreSQL
    # Hostname des PostgreSQL-Containers (nach Bedarf anpassen)
    hostname: paperless-postgres-db
    restart: unless-stopped

    # Sicherheitsoptionen
    security_opt:
      - no-new-privileges:true

   # Speicherort persistenter Daten (Pfad vor dem Doppelpunkt nach Bedarf anpassen)
    volumes:
      - /volume1/docker/paperless-ngx/pgdata:/var/lib/postgresql/18/data:rw

    # Umgebungsvariablen
    environment:
      # Datenbankname (nach Bedarf anpassen)
      POSTGRES_DB: paperless
      # Datenbankbenutzer (nach Bedarf anpassen)
      POSTGRES_USER: paperless
      # Datenbankpasswort (nach Bedarf anpassen)
      POSTGRES_PASSWORD: paperless

    # Gesundheitscheck des PostgreSQL-Containers
    healthcheck:
      #                                      Datenbankname      Datenbankbenutzer
      test: ["CMD", "pg_isready", "-q", "-d", "paperless", "-U", "paperless"]
      interval: 30s
      timeout: 10s
      retries: 5

# Paperless-ngx Container
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest

    # Name des Paperless-ngx-Containers (nach Bedarf anpassen)
    container_name: Paperless-ngx
    restart: unless-stopped

    # Sicherheitsoptionen
    security_opt:
      - no-new-privileges:true

    # Festlegung der Reihenfolge und Ausführung weiterer Dienste-Abhängigkeiten
    depends_on:
      - db
      - broker

    # Weiterleitungsport
    ports:
      - "8180:8000"

    # Gesundheitscheck des Paperless-ngx-Containers
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8000"]
        interval: 30s
        timeout: 10s
        retries: 5

    # Speicherorte persistenter Daten (Pfade vor dem Doppelpunkt nach Bedarf anpassen)
    volumes:
      - /volume1/docker/paperless-ngx/data:/usr/src/paperless/data:rw
      - /volume1/docker/paperless-ngx/media:/usr/src/paperless/media:rw
      - /volume1/docker/paperless-ngx/export:/usr/src/paperless/export:rw
      - /volume1/docker/paperless-ngx/consume:/usr/src/paperless/consume:rw

    # Umgebungsvariablen
    environment:
      # Umgebungsvariablen für Redis festlegen
      PAPERLESS_REDIS: redis://broker:6379

      # Umgebungsvariablen für PostgreSQL festlegen
      # Hostname des PostgreSQL-Containers (entspricht der Variablen "hostname" im Abschnitt "db")
      PAPERLESS_DBHOST: paperless-postgres-db
      # Datenbankname (entspricht der Variablen "POSTGRES_DB")
      PAPERLESS_DBNAME: paperless
      # Benutzername (entspricht der Variablen "POSTGRES_USER")
      PAPERLESS_DBUSER: paperless
      # Benutzername (entspricht der Variablen "POSTGRES_PASSWORD")
      PAPERLESS_DBPASS: paperless

      # Umgebungsvariablen für Paperless-ngx festlegen
      # Benutzer-ID des berechtigten Docker-Systembenutzers (nach Bedarf anpassen)
      USERMAP_UID: 1000
      # Gruppen-ID des berechtigten Docker-Systembenutzers (nach Bedarf anpassen)
      USERMAP_GID: 10
      # Name des Paperless-ngx Benutzers (nach Bedarf anpassen)
      PAPERLESS_ADMIN_USER: BENUTZERNAME
      # Passwort des Paperless-ngx Benutzers (nach Bedarf anpassen)
      PAPERLESS_ADMIN_PASSWORD: BENUTZER-PASSWORT

      # Zeitzone (nach Bedarf anpassen)
      PAPERLESS_TIME_ZONE: Europe/Berlin

      # OCR-Sprache (nach Bedarf anpassen)
      PAPERLESS_OCR_LANGUAGE: deu+eng

      # Standard-OCR-Dateinamenformat (nach Bedarf anpassen)
      PAPERLESS_FILENAME_FORMAT: '{{ correspondent }}/{{ document_type }}/{{ created_year }}-{{ created_month }}-{{ created_day }}_{{ title }}'

      # Entferne alle Platzhalter, die als "none" aufgelöst wurden.
      PAPERLESS_FILENAME_FORMAT_REMOVE_NONE: true

      # Überprüfen, ob der Dateiname ein gültiges Datum (YYYY-MM-DD) enthält. Ist dies der Fall, wird dieses anstelle des Datums im Dokument verwendet.
      PAPERLESS_FILENAME_DATE_ORDER: YMD

      # Entferne alle doppelten Dateien aus dem Ordner "Consume"
      PAPERLESS_CONSUMER_DELETE_DUPLICATES: true

      # Dateien in Unterordnern des Consumeordners erfassen
      PAPERLESS_CONSUMER_RECURSIVE: true

      # Ignoriere ein oder mehrere durch Kommas getrennte Datumsangaben in den Dokumenten
      PAPERLESS_IGNORE_DATES: "1970-01-01"

      # Die digitale Signatur von PDF-Dokumenten ungültig machen, um die OCR-Verarbeitung zu ermöglichen
      PAPERLESS_OCR_USER_ARGS: '{"invalidate_digital_signatures": true}'
