# Paperless-ngx:latest inklusive PostgreSQL 18 und Valkey 9
# YAML-Dateiversion: 1.40 vom 27.09.2026

# CHANGELOG
# - Redis 8 durch Valkey 9 ersetzt.
# - Die Startreihenfolge der Services wurde so angepasst, dass der Webserver nicht mehr nur
#   wartet, bis alle Container laufen, sondern auch, bis PostgreSQL und Valkey tatsächlich 
#   erreichbar sind.
# - Da der Healthcheck in der akuellen Paperless-ngx-Image-Definition bereits enthalten ist,
#   wurde der Healthcheck für den webserver-Service aus der Docker-Compose entfernt.


# Erstelle  einen Ordner namens „paperless-nxg” im Docker-Verzeichnis. 
# Wechsel in diesen Ordner und erstelle die folgenden Unterordner: 
# data, media, export, consume, pgdata und valkeydata.
#
# Die endgültige Verzeichnisstruktur sollte wie folgt aussehen:
# /volume1
#   /docker
#     /paperless-ngx
#       /consume
#       /data
#       /export
#       /media
#       /pgdata
#       /valkeydata

services:

# Valkey Container
  broker:
    image: docker.io/valkey/valkey:9-alpine

    # Name des Redis-Containers (nach Bedarf anpassen)
    container_name: Paperless-ngx-Valkey
    restart: unless-stopped

    # Sicherheitsoptionen
    security_opt:
      - no-new-privileges:true

    # Speicherort persistenter Daten (Pfad vor dem Doppelpunkt nach Bedarf anpassen)
    volumes:
      - /volume1/docker/paperless-ngx/valkeydata:/data:rw

    # Gesundheitscheck des Valkey-Containers
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

# PostgreSQL Container
  db:
    image: docker.io/library/postgres:18

    # Name des PostgreSQL-Containers (nach Bedarf anpassen)
    container_name: Paperless-ngx-PostgreSQL
    # Hostname des PostgreSQL-Containers (nach Bedarf anpassen)
    hostname: paperless-postgres-db
    restart: unless-stopped

    # Sicherheitsoptionen
    security_opt:
      - no-new-privileges:true

   # Speicherort persistenter Daten (Pfad vor dem Doppelpunkt nach Bedarf anpassen)
    volumes:
      - /volume1/docker/paperless-ngx/pgdata:/var/lib/postgresql/18/docker:rw

    # Umgebungsvariablen
    environment:
      # Datenbankname (nach Bedarf anpassen)
      POSTGRES_DB: paperless
      # Datenbankbenutzer (nach Bedarf anpassen)
      POSTGRES_USER: paperless
      # Datenbankpasswort (nach Bedarf anpassen)
      POSTGRES_PASSWORD: paperless

    # Gesundheitscheck des PostgreSQL-Containers
    healthcheck:
      #                                      Datenbankname      Datenbankbenutzer
      test: ["CMD", "pg_isready", "-q", "-d", "paperless", "-U", "paperless"]
      interval: 30s
      timeout: 10s
      retries: 5

# Paperless-ngx Container
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest

    # Name des Paperless-ngx-Containers (nach Bedarf anpassen)
    container_name: Paperless-ngx
    restart: unless-stopped

    # Festlegung der Reihenfolge und Ausführung weiterer Dienste-Abhängigkeiten
    depends_on:
      broker:
        condition: service_healthy
      db:
        condition: service_healthy

    # Sicherheitsoptionen
    security_opt:
      - no-new-privileges:true

    # Weiterleitungsport
    ports:
      - "8180:8000"

    # Gesundheitscheck des Paperless-ngx-Containers
    # In der aktuellen Paperless-ngx-Image-Definition ist der Healthcheck bereits standardmäßig enthalten.

    # Speicherorte persistenter Daten (Pfade vor dem Doppelpunkt nach Bedarf anpassen)
    volumes:
      - /volume1/docker/paperless-ngx/data:/usr/src/paperless/data:rw
      - /volume1/docker/paperless-ngx/media:/usr/src/paperless/media:rw
      - /volume1/docker/paperless-ngx/export:/usr/src/paperless/export:rw
      - /volume1/docker/paperless-ngx/consume:/usr/src/paperless/consume:rw

    # Umgebungsvariablen
    environment:

      # Umgebungsvariablen für PostgreSQL festlegen
      # Festlegung der verwendeten Datenbank-Engine. Zulässige Werte sind „sqlite“, „postgresql“ und „mariadb“.
      PAPERLESS_DBENGINE: postgresql
      # Hostname des PostgreSQL-Containers (entspricht der Variablen "hostname" im Abschnitt "db")
      PAPERLESS_DBHOST: paperless-postgres-db
      # Datenbankname (entspricht der Variablen "POSTGRES_DB" des Dienstes "db")
      PAPERLESS_DBNAME: paperless
      # Benutzername (entspricht der Variablen "POSTGRES_USER" des Dienstes "db")
      PAPERLESS_DBUSER: paperless
      # Benutzername (entspricht der Variablen "POSTGRES_PASSWORD" des Dienstes "db")
      PAPERLESS_DBPASS: paperless

      # Umgebungsvariablen für Valkey festlegen (Das hier die Bezeichnung redis verwendet wird ist korrekt!)
      PAPERLESS_REDIS: redis://broker:6379

      # Umgebungsvariablen für den Paperless-ngx-Container festlegen
      # Benutzer-ID des berechtigten Docker-Systembenutzers (nach Bedarf anpassen)
      USERMAP_UID: 1000
      # Gruppen-ID des berechtigten Docker-Systembenutzers (nach Bedarf anpassen)
      USERMAP_GID: 10
      # Name des Paperless-ngx Benutzers (nach Bedarf anpassen)
      PAPERLESS_ADMIN_USER: admin-user
      # Passwort des Paperless-ngx Benutzers (nach Bedarf anpassen)
      PAPERLESS_ADMIN_PASSWORD: admin-password
      # Für den Sitzungstoken und die Signierung ist ein eindeutiger, mindestens 64 Zeichen langer, geheimer Schlüssel erforderlich.
      # Die Generierung kann beispielsweise über die Linux-Kommandozeile mithilfe des folgenden Befehls erfolgen.
      # python3 -c "import secrets; print(secrets.token_urlsafe(64))"
      PAPERLESS_SECRET_KEY: change-me
      # Zeitzone (nach Bedarf anpassen)
      PAPERLESS_TIME_ZONE: Europe/Berlin
      # OCR-Sprache (nach Bedarf anpassen)
      PAPERLESS_OCR_LANGUAGE: deu+eng
      # Standard-OCR-Dateinamenformat (nach Bedarf anpassen)
      PAPERLESS_FILENAME_FORMAT: '{{ correspondent }}/{{ document_type }}/{{ created_year }}-{{ created_month }}-{{ created_day }}_{{ title }}'
      # Entferne alle Platzhalter, die als "none" aufgelöst wurden.
      PAPERLESS_FILENAME_FORMAT_REMOVE_NONE: true
      # Entferne alle doppelten Dateien aus dem Ordner "Consume"
      PAPERLESS_CONSUMER_DELETE_DUPLICATES: true
      # Dateien in Unterordnern des Consumeordners erfassen
      PAPERLESS_CONSUMER_RECURSIVE: true
      # Die digitale Signatur von PDF-Dokumenten ungültig machen, um die OCR-Verarbeitung zu ermöglichen
      PAPERLESS_OCR_USER_ARGS: '{"invalidate_digital_signatures": true}'

